# GitLab CI configuration for K6 Test Explorer VS Code Extension

# Define stages
stages:
  - install
  - test
  - build
  - package
  - release

# Global variables
variables:
  NODE_VERSION: "18"
  CACHE_KEY: "$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG"

# Cache configuration for node_modules
.node_cache: &node_cache
  cache:
    key: "$CACHE_KEY"
    paths:
      - node_modules/
      - .npm/
    policy: pull

.node_cache_push: &node_cache_push
  cache:
    key: "$CACHE_KEY"
    paths:
      - node_modules/
      - .npm/
    policy: push

# Install dependencies
install_dependencies:
  stage: install
  image: node:$NODE_VERSION-alpine
  <<: *node_cache_push
  before_script:
    - npm config set cache .npm
  script:
    - npm ci --prefer-offline --no-audit
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/
  only:
    - merge_requests
    - master
    - develop
    - tags

# Lint code
lint:
  stage: test
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["install_dependencies"]
  script:
    - npm run lint
  only:
    - merge_requests
    - master
    - develop
    - tags

# Type checking
type_check:
  stage: test
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["install_dependencies"]
  script:
    - npm run check-types
  only:
    - merge_requests
    - master
    - develop
    - tags

# Run tests
test:
  stage: test
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["install_dependencies"]
  before_script:
    # Install Xvfb for running VS Code tests in headless mode
    - apk add --no-cache xvfb
  script:
    - npm run compile-tests
    - xvfb-run -a npm run test
  coverage: '/Lines\s*:\s*(\d+\.\d+)%/'
  artifacts:
    reports:
      junit: test-results.xml
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - merge_requests
    - master
    - develop
    - tags

# Build the extension
build:
  stage: build
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["install_dependencies", "lint", "type_check"]
  script:
    - npm run compile
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  only:
    - merge_requests
    - master
    - develop
    - tags

# Package the extension
package:
  stage: package
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["build"]
  before_script:
    - npm install -g vsce
  script:
    - npm run package
    - vsce package --out k6-test-explorer-$CI_COMMIT_SHORT_SHA.vsix
  artifacts:
    paths:
      - "*.vsix"
    expire_in: 1 week
  only:
    - merge_requests
    - master
    - develop
    - tags

# Security scanning
security_scan:
  stage: test
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["install_dependencies"]
  script:
    - npm audit --audit-level=moderate
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop

# Release job for tags
release:
  stage: release
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["package", "test"]
  before_script:
    - npm install -g vsce
  script:
    - vsce package --out k6-test-explorer-$CI_COMMIT_TAG.vsix
    - echo "Extension packaged for release $CI_COMMIT_TAG"
  artifacts:
    paths:
      - "*.vsix"
    expire_in: 30 days
  only:
    - tags
  when: manual

# Deploy to VS Code Marketplace (manual job for tags)
deploy_marketplace:
  stage: release
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["release"]
  before_script:
    - npm install -g vsce
  script:
    - echo "To deploy to marketplace, run:"
    - echo "vsce publish --pat YOUR_PERSONAL_ACCESS_TOKEN"
    - echo "Extension ready for marketplace deployment"
  only:
    - tags
  when: manual
  environment:
    name: marketplace
    url: https://marketplace.visualstudio.com/

# Job for development builds
dev_build:
  stage: package
  image: node:$NODE_VERSION-alpine
  <<: *node_cache
  needs: ["build"]
  before_script:
    - npm install -g vsce
  script:
    - vsce package --out k6-test-explorer-dev-$CI_COMMIT_SHORT_SHA.vsix
  artifacts:
    paths:
      - "*.vsix"
    expire_in: 3 days
  only:
    - develop
    - merge_requests
  except:
    - tags
